apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerNoPrivilege
metadata:
  name: container-no-privilege
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    namespaceSelector: {{ .Values.namespaceSelector }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]