  
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureIngressHttpsOnly
metadata:
  name: ingress-https-only
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
