apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerProbesRequired
metadata:
  name: container-probes-required
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    probes : {{ .Values.requiredProbes }}
    probeTypes: {{ .Values.supportedProbeTypes }}