# Default values for azure policy add-on on AKS Engine, a self-managed Kubernetes cluster on Azure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Microsoft Azure Policy Add-on on AKS Engine
azurepolicy:
  image:
    name: "mcr.microsoft.com/azure-policy/policy-kubernetes-addon-prod"
    tag: "prod_20200519.1"
## Resource ID for AKS Engine is the ID of the resource group the AKS Engine cluster is in.
  env:
    resourceid: <your_resource_id>

## OPA Gatekeeper for Kubernetes clusters
gatekeeper:
  image:
    name: "mcr.microsoft.com/oss/open-policy-agent/gatekeeper"
    tag: "v3.1.0-beta.8"
  args:
    auditIntervalSeconds: 60
    constraintViolationsLimit: 100
  resources:
    cpuLimit: 1000m
    memoryLimit: 512Mi
    cpuRequests: 100m
    memoryRequests: 256Mi

## Alpine image used in the helm hook
alpine:
  image:
    name: "mcr.microsoft.com/azure-policy/alpine"
    tag: "prod_20200505.1"
