apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureReadOnlyRootFilesystem
metadata:
  name: psp-readonly-root-filesystem
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    namespaceSelector: {{ .Values.namespaceSelector }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
