apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerAllowedImages
metadata:
  name: container-allowed-images
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
      - key: control-plane
        operator: DoesNotExist
  parameters:
    imageRegex: {{ .Values.allowedContainerImagesRegex }}
